/** Data-only HP-QA-01 capture matrix. Bump when framing or scenarios change. */
export const GOLDEN_MATRIX_VERSION = 3;

const stage = { capture: 'stage', threshold: { maxChannelDelta: 10, maxDiffRatio: 0.0005 } };
const page = { capture: 'page', threshold: { maxChannelDelta: 10, maxDiffRatio: 0.0008 } };

export const GOLDEN_SCENARIOS = Object.freeze([
  { id: 'geometry-view-dark-fit', fixture: 'visual', space: 'golden-geometry', mode: 'view',
    theme: 'dark', viewport: { width: 1000, height: 900 }, ...stage },
  { id: 'geometry-view-light-fit', fixture: 'visual', space: 'golden-geometry', mode: 'view',
    theme: 'light', viewport: { width: 1000, height: 900 }, ...stage },
  { id: 'geometry-plan-editor-dark', fixture: 'visual', space: 'golden-geometry', mode: 'plan',
    theme: 'dark', viewport: { width: 1180, height: 900 }, ...page },
  { id: 'geometry-devices-editor-dark', fixture: 'visual', space: 'golden-geometry', mode: 'devices',
    theme: 'dark', viewport: { width: 1180, height: 900 }, ...page },
  { id: 'geometry-decor-editor-dark', fixture: 'visual', space: 'golden-geometry', mode: 'decor',
    theme: 'dark', viewport: { width: 1180, height: 900 }, ...page },
  // HP-UX-11 visual contract: every adaptive width is captured in both
  // languages while the six materially different tray contents are open.
  { id: 'tray-wide-selection-en', fixture: 'visual', space: 'golden-geometry', mode: 'plan',
    editorTray: 'plan-selection', language: 'en', theme: 'dark',
    viewport: { width: 1180, height: 900 }, ...page },
  { id: 'tray-wide-tool-ru', fixture: 'visual', space: 'golden-geometry', mode: 'plan',
    editorTray: 'plan-tool', language: 'ru', theme: 'dark',
    viewport: { width: 1180, height: 900 }, ...page },
  { id: 'tray-medium-group-en', fixture: 'visual', space: 'golden-geometry', mode: 'plan',
    editorTray: 'group', language: 'en', theme: 'dark',
    viewport: { width: 760, height: 820 }, ...page },
  { id: 'tray-medium-selection-ru', fixture: 'visual', space: 'golden-geometry', mode: 'decor',
    editorTray: 'decor-selection', language: 'ru', theme: 'dark',
    viewport: { width: 760, height: 820 }, ...page },
  { id: 'tray-narrow-palette-en', fixture: 'visual', space: 'golden-geometry', mode: 'decor',
    editorTray: 'furniture-palette', language: 'en', theme: 'dark',
    viewport: { width: 390, height: 760 }, ...page },
  { id: 'tray-narrow-tool-ru', fixture: 'visual', space: 'golden-geometry', mode: 'decor',
    editorTray: 'decor-tool', language: 'ru', theme: 'dark',
    viewport: { width: 390, height: 760 }, ...page },
  { id: 'geometry-diagonal-45-opening-dark', fixture: 'visual', space: 'golden-geometry', mode: 'view',
    theme: 'dark', viewport: { width: 1000, height: 900 }, ...stage },
  { id: 'openings-thick-wall-dark', fixture: 'visual', space: 'golden-lighting', mode: 'view',
    fillMode: 'none', theme: 'dark', viewport: { width: 1000, height: 900 }, ...stage },
  { id: 'openings-hidden-view-dark', fixture: 'visual', space: 'golden-lighting', mode: 'view',
    fillMode: 'none', hideOpenings: true, theme: 'dark', viewport: { width: 1000, height: 900 }, ...stage },
  { id: 'lighting-glow-sun-dark', fixture: 'visual', space: 'golden-lighting', mode: 'view',
    theme: 'dark', viewport: { width: 1000, height: 900 }, ...stage },
  { id: 'lighting-fill-light-axis-split-dark', fixture: 'visual', space: 'golden-lighting', mode: 'view',
    fillMode: 'light', theme: 'dark', viewport: { width: 1000, height: 900 }, ...stage },
  { id: 'lighting-fill-temp-axis-split-dark', fixture: 'visual', space: 'golden-lighting', mode: 'view',
    fillMode: 'temp', theme: 'dark', viewport: { width: 1000, height: 900 }, ...stage },
  { id: 'lighting-fill-lqi-axis-split-dark', fixture: 'visual', space: 'golden-lighting', mode: 'view',
    fillMode: 'lqi', theme: 'dark', viewport: { width: 1000, height: 900 }, ...stage },
  { id: 'hover-over-glow-dark', fixture: 'visual', space: 'golden-lighting', mode: 'view',
    hoverRoom: 'light-right', theme: 'dark', viewport: { width: 1000, height: 900 }, ...stage },
  { id: 'hover-nested-room-dark', fixture: 'visual', space: 'golden-geometry', mode: 'view',
    hoverRoom: 'geo-nested', theme: 'dark', viewport: { width: 1000, height: 900 }, ...stage },
  { id: 'large-house-zoom-040-dark', fixture: 'large', space: 'perf-floor-1', mode: 'view',
    zoom: 0.4, theme: 'dark', viewport: { width: 1180, height: 900 }, ...stage },
  { id: 'large-house-zoom-250-dark', fixture: 'large', space: 'perf-floor-1', mode: 'view',
    zoom: 2.5, theme: 'dark', viewport: { width: 1180, height: 900 }, ...stage },
  { id: 'large-house-warm-remount-dark', fixture: 'large', space: 'perf-floor-2', mode: 'view',
    warmRemount: true, theme: 'dark', viewport: { width: 1180, height: 900 }, ...stage },
  { id: 'device-dialog-desktop-en', fixture: 'visual', space: 'golden-lighting',
    dialog: 'device', deviceId: 'golden-climate',
    deviceName: 'Living room climate controller with an intentionally long title',
    focusDialogClose: true, language: 'en', theme: 'dark', viewport: { width: 1180, height: 900 }, ...page },
  { id: 'device-dialog-mobile-ru', fixture: 'visual', space: 'golden-lighting',
    dialog: 'device', deviceId: 'golden-climate',
    deviceName: 'Контроллер климата гостиной с намеренно очень длинным названием',
    language: 'ru', theme: 'dark', viewport: { width: 390, height: 760 }, ...page },
  { id: 'decor-color-popover-mobile-ru', fixture: 'visual', space: 'golden-geometry',
    dialog: 'decor-color', language: 'ru', theme: 'dark',
    viewport: { width: 390, height: 760 }, ...page },
]);
